#!/bin/bash

tar -zcf tiaotiao.tgz \
    start \
    gameserver.ini \
    client.js \
    package.json \
    src \
    node_modules

scp tiaotiao.tgz agar:
rm -rf tiaotiao.tgz
ssh agar "mkdir -pv tiaotiao && tar -mzxf tiaotiao.tgz -C tiaotiao && ./tiaotiao/start";
