#!/bin/bash

tar -zcf tiaotiao.tgz \
    start \
    client.js \
    package.json \
    src \
    node_modules

#scp tiaotiao.tgz agar:
#rm -rf tiaotiao.tgz
#ssh agar "mkdir -pv tiaotiao && tar -mzxf tiaotiao.tgz -C tiaotiao && ./tiaotiao/start 1448 1>/dev/null";

scp tiaotiao.tgz agar1:
rm -rf tiaotiao.tgz
ssh agar1 "mkdir -pv tiaotiao && tar -mzxf tiaotiao.tgz -C tiaotiao && ./tiaotiao/start 1449 1>/dev/null";
